// SPDX-License-Identifier: GPL-3.0-or-later
//
// GENERATED by scripts/geo_ucode.py --export; edit that, not this.
//
// The geometry microcode's entry points and the registers the glue writes (1683 words).

package hng64_geo_ucode_pkg;
    localparam int GEO_ENTRY_INIT = 0;
    localparam int GEO_ENTRY_CLEAR = 56;
    localparam int GEO_ENTRY_UPLOAD = 98;
    localparam int GEO_REG_SAMSHO = 13;
    localparam int GEO_REG_VLEN = 14;
endpackage
