// SPDX-License-Identifier: GPL-3.0-or-later
//
// Toshiba TLCS-870 (TMP87PH40AN), the HNG64's IO MCU. Transcribed from MAME's
// src/devices/cpu/tlcs870/, which is the accuracy reference: where MAME and the Toshiba manual
// disagree this follows MAME, and each place is in docs/MAME_KLUDGES.md.
//
// SHAPE
// -----
// MAME executes an instruction atomically and charges it a cycle count (`m_cycles`, one tick of
// the 8 MHz clock). This does the same: a sequencer runs at the core clock and takes as many
// steps as the work needs, and the instruction retires only once `cycles` ticks of `ce` have
// passed since its fetch began. Reset, interrupt entry, fetch, the prefixes' addressing and the
// operand bytes are logic here; each instruction's execute phase is a microprogram
// (hng64_tlcs870_ucode, generated by scripts/tlcs870_ucode.py), which with the opcode dispatch
// took this module from 2,816 ALMs to 1,165 and five M10K (fitted alone). Instruction boundaries therefore land where MAME's do,
// which is what decides when an interrupt is taken. `dbg_overrun` fires if an instruction needs
// more core clocks than its budget allows: on clk1x (62.5 MHz) there are 7.8 clocks a tick and
// sim/iomcu_tb runs without one at 5, but a silent overrun would be a timing difference nothing
// else would show.
//
// BUS TIMING - THE ONE RULE TO KEEP IN MIND
// -----------------------------------------
// The port's outputs are registered, so a request set up on step S is on the port during S+1 and
// its data is on `din` during S+2. Every read below is written as "issue at S, use at S+2", and
// back-to-back issues pipeline: reads at S and S+1 give their bytes at S+2 and S+3.
//
// REGISTERS ARE MEMORY
// --------------------
// `get_reg8` is `intram[(RBS & 0xf) * 8 + (reg & 7)]` (tlcs870_ops_helper.cpp:17) and intram is
// mapped at 0x0040, so register r of bank RBS is the byte at 0x0040 + RBS*8 + r and the program
// can reach it as ordinary RAM. Register access goes through the same port, not a separate file.
//
// This module owns the SFRs that are CPU state rather than peripheral state - EIR (0x3a/0x3b),
// IL (0x3c/0x3d) and PSW/RBS (0x3f) - and answers them itself. Everything else leaves the port.
//
// A read of an I/O port normally sees the pins, but MAME clears `m_read_input_port` in a set of
// read-modify-write handlers so that they see the port's output latch instead (tlcs870.cpp:140).
// `mem_latch` marks those reads. They are: SET/CLR (x).b; CLR/CPL (pp).g; and from the source
// prefix XCH, SET/CLR/CPL (src).b, LD (src).b,CF and every ALUOP (src) form except CMP. SET
// (pp).g and LD (pp).g,CF read the pins, as MAME's do.
//
// All three prefix families are implemented: source (0xe0-0xe7), register (0xe8-0xef) and
// destination (0xf0-0xf7). An opcode with no handler raises `dbg_unimpl` and sim/iomcu_tb
// names the pair that did it.

module hng64_tlcs870 (
    input  logic        clk,
    input  logic        reset,
    input  logic        ce,             // one pulse per MCU clock

    output logic [15:0] mem_addr,
    output logic        mem_rd,
    output logic        mem_we,
    output logic        mem_latch,      // with mem_rd: a port read sees the output latch
    output logic  [7:0] mem_wdata,
    input  logic  [7:0] mem_rdata,      // valid the clock after mem_rd

    input  logic [15:0] irq,            // level per IL bit; a rising edge latches

    // per-instruction export, for sim/iomcu_tb
    output logic        dbg_fetch,      // one clock, as an instruction's opcode arrives
    output logic [15:0] dbg_pc,         // that instruction's address
    output logic  [7:0] dbg_op,
    output logic  [7:0] dbg_op1,
    output logic        dbg_unimpl,     // sticky: an opcode this does not implement
    output logic        dbg_overrun,    // sticky: an instruction outran its cycle budget
    output logic [15:0] dbg_sp,
    output logic  [3:0] dbg_rbs,
    output logic  [7:0] dbg_f
);

    localparam logic [7:0] FLAG_J = 8'h80;
    localparam logic [7:0] FLAG_Z = 8'h40;
    localparam logic [7:0] FLAG_C = 8'h20;

    localparam logic [2:0] REG_A = 3'd0, REG_C = 3'd2;

    // ---- state ---------------------------------------------------------------------------------
    logic [15:0] pc;                    // MAME's m_addr: advances through the operand bytes
    logic [15:0] tmppc;                 // the instruction's own address, the base for branches
    logic [15:0] sp;
    logic  [7:0] f;
    logic  [3:0] rbs;
    logic [15:0] eir, il, irq_d;

    logic  [7:0] op0, op1;
    logic  [7:0] pimm;                  // a prefix's own address immediate, (x) or (HL+d)
    logic  [7:0] imm0, imm1, imm2;
    logic  [1:0] imm_need, imm_got;
    logic  [4:0] cycles;
    logic  [7:0] elapsed;
    logic  [5:0] step;
    logic [15:0] ea;
    logic  [7:0] tmp8;
    logic [15:0] tmp16;
    logic [15:0] acc;                   // MUL/DIV accumulator
    logic  [7:0] mcnt;

    typedef enum logic [3:0] { P_RESET, P_FETCH, P_PFX, P_EA, P_IMM, P_EXEC, P_PACE,
                               P_INT } phase_t;
    phase_t ph;

    assign dbg_sp  = sp;
    assign dbg_rbs = rbs;
    assign dbg_f   = f;
    assign dbg_op  = op0;
    assign dbg_op1 = op1;

    // ---- ALU: operands are registered, the result is valid the next step -----------------------
    logic  [2:0] alu_op;
    logic        alu_wide;
    logic [15:0] alu_a, alu_b;
    logic [15:0] alu_r;
    logic  [7:0] alu_f;

    hng64_tlcs870_alu u_alu (.op(alu_op), .wide(alu_wide), .a(alu_a), .b(alu_b), .f_in(f),
                             .result(alu_r), .f_out(alu_f));

    logic  [2:0] sh_op;
    logic  [7:0] sh_v;
    logic  [7:0] sh_r, sh_f;

    hng64_tlcs870_shift u_shift (.op(sh_op), .v(sh_v), .f_in(f), .result(sh_r), .f_out(sh_f));

    // ---- the memory port, and the SFRs this module answers itself ------------------------------
    logic [15:0] a_q;
    logic        rd_q, we_q, latch_q;
    logic  [7:0] wd_q;
    logic        sfr_rd;
    logic  [7:0] sfr_val;

    assign mem_addr  = a_q;
    assign mem_wdata = wd_q;

    function automatic logic own_sfr(input logic [15:0] a);
        own_sfr = (a == 16'h003a) || (a == 16'h003b) || (a == 16'h003c)
               || (a == 16'h003d) || (a == 16'h003f);
    endfunction

    assign mem_rd    = rd_q && !own_sfr(a_q);
    assign mem_we    = we_q && !own_sfr(a_q);
    assign mem_latch = latch_q;

    wire [7:0] din = sfr_rd ? sfr_val : mem_rdata;
    wire [7:0] psw = {f[7:4], rbs};

    function automatic logic [15:0] reg8_addr(input logic [3:0] bank, input logic [2:0] r);
        reg8_addr = 16'h0040 + {9'd0, bank, 3'd0} + {13'd0, r};
    endfunction

    wire [15:0] ra_a   = reg8_addr(rbs, REG_A);
    wire [15:0] ra_c   = reg8_addr(rbs, REG_C);

    wire [15:0] imm0_a  = {8'd0, imm0};

    // The prefix families name a register in the PREFIX byte - g = op0[2:0] for 8-bit forms,
    // gg = op0[1:0] for 16-bit ones - and a second register or a bit in the byte after it.
    wire        is_reg_pfx = (op0[7:3] == 5'b11101);
    wire        is_src_pfx = (op0[7:3] == 5'b11100);
    wire        cf = |(f & FLAG_C);

    // get_addr (tlcs870_ops_helper.cpp:118). The mode is the prefix byte's low three bits:
    // 0 (x), 1 (PC+A), 2 (DE), 3 (HL), 4 (HL+d), 5 (HL+C), 6 (HL+), 7 (-HL).
    wire  [2:0] ea_mode = op0[2:0];
    wire        ea_imm  = (ea_mode == 3'd0) || (ea_mode == 3'd4);
    wire        pfx_lead_imm = !is_reg_pfx && ea_imm;
    // where P_EA leaves: after `ea` is computed, and after the (HL+)/(-HL)
    // writeback where there is one
    wire  [5:0] ea_done = (ea_mode == 3'd0) ? 6'd0
                        : (ea_mode == 3'd1) ? 6'd2
                        : (ea_mode == 3'd6 || ea_mode == 3'd7) ? 6'd6 : 6'd4;
    wire [15:0] ra_ea0  = reg8_addr(rbs, (ea_mode == 3'd2) ? 3'd4 : 3'd6);
    wire [15:0] ra_ea1  = reg8_addr(rbs, (ea_mode == 3'd2) ? 3'd5 : 3'd7);

    // get_base_srcdst_cycles (tlcs870.h:366)
    function automatic logic [4:0] base_cycles(input logic [2:0] m);
        case (m)
            3'd0: base_cycles = 5'd1;
            3'd1: base_cycles = 5'd2;
            3'd2, 3'd3: base_cycles = 5'd0;
            3'd4, 3'd5: base_cycles = 5'd2;
            default: base_cycles = 5'd1;
        endcase
    endfunction

    // ---- condition codes (check_jump_condition, tlcs870_ops_helper.cpp:163) --------------------
    function automatic logic cond_met(input logic [2:0] c, input logic [7:0] fl);
        case (c)
            3'd0: cond_met =  |(fl & FLAG_Z);                   // EQ / Z
            3'd1: cond_met = ~|(fl & FLAG_Z);                   // NE / NZ
            3'd2: cond_met =  |(fl & FLAG_C);                   // LT / CS
            3'd3: cond_met = ~|(fl & FLAG_C);                   // GE / CC
            3'd4: cond_met =  |(fl & (FLAG_C | FLAG_Z));        // LE
            3'd5: cond_met = ~|(fl & (FLAG_C | FLAG_Z));        // GT
            3'd6: cond_met =  |(fl & FLAG_J);                   // T
            default: cond_met = ~|(fl & FLAG_J);                // F
        endcase
    endfunction

    // flags for the "JF and ZF both follow zero-ness" pattern the INC/DEC/bit ops use
    function automatic logic [7:0] set_zj(input logic [7:0] fl, input logic z);
        set_zj = (fl & ~(FLAG_Z | FLAG_J)) | (z ? (FLAG_Z | FLAG_J) : 8'd0);
    endfunction

    // ---- the microcode: the execute phase, one ROM word a step ------------------------------------
    // scripts/tlcs870_ucode.py generates hng64_tlcs870_ucode (the ROM and the dispatch) from the
    // step sequences, keeping each one's bus timing; the field codes below are its. A word comes out
    // the clock after its address, so the address is always the NEXT step's: the entry while an
    // instruction is being decoded, then upc + 1, or upc again while a MUL/DIV loop runs.
    localparam logic [1:0] B_RD = 2'd1, B_RDX = 2'd2, B_WR = 2'd3;
    localparam logic [1:0] Q_FIN = 2'd1, Q_MUL = 2'd2, Q_DIV = 2'd3;

    logic  [9:0] upc, uaddr, entry_q;
    logic [45:0] uw;
    logic  [1:0] d_fam;
    logic  [9:0] d_entry;
    logic  [1:0] d_imm;
    logic  [4:0] d_cyc;

    hng64_tlcs870_ucode u_uc (.clk(clk), .uaddr(uaddr), .uword(uw), .fam(d_fam), .op(din),
                              .entry(d_entry), .imm(d_imm), .cyc(d_cyc));

    wire  [1:0] u_bus    = uw[1:0];
    wire  [3:0] u_asel   = uw[5:2];
    wire  [3:0] u_rsel   = uw[9:6];
    wire  [4:0] u_wsel   = uw[14:10];
    wire  [4:0] u_ld     = uw[19:15];
    wire  [4:0] u_flag   = uw[24:20];
    wire  [2:0] u_sp     = uw[27:25];
    wire  [3:0] u_pc     = uw[31:28];
    wire  [1:0] u_seq    = uw[33:32];
    wire  [2:0] u_misc   = uw[36:34];
    wire        u_alusrc = uw[37];
    wire  [1:0] u_bop    = uw[39:38];
    wire  [1:0] u_msel   = uw[41:40];
    wire        u_bsrc   = uw[42];
    wire  [2:0] u_shop   = uw[45:43];

    // the opcode byte is in `din` in the last step of P_FETCH, and of P_PFX
    wire latch_base = (ph == P_FETCH) && (step >= 6'd2);
    wire latch_pfx  = (ph == P_PFX) && (step == (pfx_lead_imm ? 6'd2 : 6'd1));
    assign d_fam = !latch_pfx ? 2'd0 : is_reg_pfx ? 2'd1 : is_src_pfx ? 2'd2 : 2'd3;

    // the register a step names: fixed, or from the opcode bytes
    logic [2:0] u_ridx;
    always_comb
        case (u_rsel)
            4'd8:    u_ridx = op0[2:0];
            4'd9:    u_ridx = {op0[1:0], 1'b0};
            4'd10:   u_ridx = {op0[1:0], 1'b1};
            4'd11:   u_ridx = op1[2:0];
            4'd12:   u_ridx = {op1[1:0], 1'b0};
            4'd13:   u_ridx = {op1[1:0], 1'b1};
            4'd14:   u_ridx = {1'b1, op1[0], 1'b0};    // (pp): DE or HL
            4'd15:   u_ridx = {1'b1, op1[0], 1'b1};
            default: u_ridx = u_rsel[2:0];
        endcase
    wire [15:0] u_ra = reg8_addr(rbs, u_ridx);

    logic [15:0] u_addr;
    always_comb
        case (u_asel)
            4'd1:    u_addr = imm0_a;
            4'd2:    u_addr = imm0_a + 16'd1;
            4'd3:    u_addr = {8'd0, imm1};
            4'd4:    u_addr = tmp16;
            4'd5:    u_addr = tmp16 + 16'd1;
            4'd6:    u_addr = ea;
            4'd7:    u_addr = ea + 16'd1;
            4'd8:    u_addr = sp;
            4'd9:    u_addr = sp - 16'd1;
            4'd10:   u_addr = sp + 16'd1;
            4'd11:   u_addr = sp + 16'd2;
            4'd12:   u_addr = sp + 16'd3;
            4'd13:   u_addr = {din, tmp16[7:0]};
            default: u_addr = u_ra;
        endcase

    // the bit operations: a byte (din or tmp8) against a mask from op0, op1 or tmp8
    wire [7:0] u_bval  = u_bsrc ? tmp8 : din;
    wire [7:0] u_bmask = (u_msel == 2'd0) ? (8'd1 << op0[2:0])
                       : (u_msel == 2'd1) ? (8'd1 << op1[2:0]) : (8'd1 << tmp8[2:0]);
    wire       u_bit   = (u_bval & u_bmask) != 8'd0;
    logic [7:0] u_bres;
    always_comb
        case (u_bop)
            2'd0:    u_bres = u_bval | u_bmask;
            2'd1:    u_bres = u_bval & ~u_bmask;
            2'd2:    u_bres = u_bval ^ u_bmask;
            default: u_bres = cf ? (u_bval | u_bmask) : (u_bval & ~u_bmask);
        endcase

    logic [7:0] u_wd;
    always_comb
        case (u_wsel)
            5'd1:    u_wd = tmp8;
            5'd2:    u_wd = imm0;
            5'd3:    u_wd = imm1;
            5'd4:    u_wd = imm2;
            5'd5:    u_wd = 8'd0;
            5'd6:    u_wd = alu_r[7:0];
            5'd7:    u_wd = alu_r[15:8];
            5'd8:    u_wd = sh_r;
            5'd9:    u_wd = psw;
            5'd10:   u_wd = pc[7:0];
            5'd11:   u_wd = pc[15:8];
            5'd12:   u_wd = tmp16[7:0];
            5'd13:   u_wd = tmp16[15:8];
            5'd14:   u_wd = ea[7:0];
            5'd15:   u_wd = ea[15:8];
            5'd16:   u_wd = acc[7:0];
            5'd17:   u_wd = sp[7:0];
            5'd18:   u_wd = sp[15:8];
            5'd19:   u_wd = u_bres;
            5'd20:   u_wd = {din[7:4], tmp8[7:4]};        // ROLD: A
            5'd21:   u_wd = {din[7:4], tmp8[3:0]};        // RORD: A
            5'd22:   u_wd = tmp16[7:0] + 8'd1;
            5'd23:   u_wd = tmp16[7:0] - 8'd1;
            default: u_wd = din;
        endcase

    wire [2:0] u_aluop = u_alusrc ? op1[2:0] : op0[2:0];
    // RETN exists only as 0xe8 0x04
    wire       u_bad   = (u_misc == 3'd4) && (op0 != 8'he8);
    // MUL and DIV iterate in one step; DIV writes the quotient's low byte from it when it is done
    wire       u_muldone = mcnt == 8'd8;
    wire       u_div0    = ea[7:0] == 8'd0;
    wire       u_divdone = mcnt == 8'd16;
    wire       u_stay    = (u_seq == Q_MUL && !u_muldone) || (u_seq == Q_DIV && !u_div0 && !u_divdone);

    always_comb
        if (ph == P_EXEC)                 uaddr = u_stay ? upc : upc + 10'd1;
        else if (latch_base || latch_pfx) uaddr = d_entry;
        else                              uaddr = entry_q;

    always_ff @(posedge clk) begin
        upc <= uaddr;
        if (latch_base || latch_pfx) entry_q <= d_entry;
    end

    // ---- interrupts (check_interrupts, tlcs870.cpp:954) ----------------------------------------
    // Priorities 0..2 are non-maskable and MAME does not implement them; 3..15 need EIR bit 0.
    // MAME's loop runs upwards and returns on the first match, so the lowest index wins.
    logic [3:0] int_pri;
    logic       int_pending;

    always_comb begin
        int_pri = 4'd0;
        int_pending = 1'b0;
        for (int p = 15; p >= 3; p--) begin
            if (eir[0] && il[p]) begin
                int_pri = 4'(p);
                int_pending = 1'b1;
            end
        end
    end

    // the JRS displacement is 5 bits signed, the JR one 8; both are added to tmppc + 2
    wire [15:0] jrs_target = tmppc + 16'd2 + {{11{op0[4]}}, op0[4:0]};
    wire [15:0] jr_target  = tmppc + 16'd2 + {{8{imm0[7]}}, imm0};

    // ---- the sequencer --------------------------------------------------------------------------
    logic [15:0] il_n, eir_n;

    task automatic finish;
        ph <= P_PACE;
        step <= 6'd0;
    endtask

    // The bus request is built with blocking assignments into these and registered once, at the
    // end of the process. These are macros rather than tasks because a task that assigns module
    // variables counts as a second driver of them, which buries a real multiple-driver warning
    // among false ones.
    logic [15:0] a_d;
    logic        rd_d, we_d, latch_d;
    logic  [7:0] wd_d;

`define RD(A)     begin a_d = (A); rd_d = 1'b1; end
`define RDX(A, L) begin a_d = (A); rd_d = 1'b1; latch_d = (L); end
`define WR(A, D)  begin a_d = (A); we_d = 1'b1; wd_d = (D); end
`define FIN       begin ph <= P_PACE; step <= 6'd0; end

    always_ff @(posedge clk) begin
        a_d  = 16'd0;
        rd_d = 1'b0;
        we_d = 1'b0;
        wd_d = 8'd0;
        latch_d = 1'b0;
        dbg_fetch <= 1'b0;

        // the reply pipeline: what was on the port last cycle decides what `din` carries now
        sfr_rd  <= rd_q && own_sfr(a_q);
        sfr_val <= (a_q == 16'h003a) ? eir[7:0]
                 : (a_q == 16'h003b) ? eir[15:8]
                 : (a_q == 16'h003c) ? il[7:0]
                 : (a_q == 16'h003d) ? il[15:8]
                 : psw;

        irq_d <= irq;
        il_n  = il | (irq & ~irq_d);            // set_irq_line: a rising edge latches
        eir_n = eir;

        if (we_q && own_sfr(a_q)) begin
            case (a_q)
                16'h003a: eir_n = {eir[15:8], wd_q};
                16'h003b: eir_n = {wd_q, eir[7:0]};
                16'h003c: il_n  = {il[15:8], wd_q};
                // MAME's il_h_w takes the low byte from EIR, not IL (tlcs870.cpp:887); see
                // docs/MAME_KLUDGES.md
                16'h003d: il_n  = {wd_q, eir[7:0]};
                default:  rbs   <= wd_q[3:0];   // rbs_w: the flags cannot be written here
            endcase
        end

        if (ce) elapsed <= elapsed + 8'd1;
        if (ph == P_EXEC && elapsed > {3'd0, cycles} + 8'd2) dbg_overrun <= 1'b1;

        if (reset) begin
            ph <= P_RESET;
            step <= 6'd0;
            sp <= 16'd0;
            f <= 8'd0;
            rbs <= 4'd0;
            eir_n = 16'd0;
            il_n = 16'd0;
            irq_d <= 16'd0;
            elapsed <= 8'd0;
            dbg_unimpl <= 1'b0;
            dbg_overrun <= 1'b0;
        end else begin
            case (ph)
                // device_reset: m_pc = RM16(0xfffe)
                P_RESET: begin
                    step <= step + 6'd1;
                    case (step)
                        6'd0: `RD(16'hfffe)
                        6'd1: `RD(16'hffff)
                        6'd2: tmp8 <= din;
                        default: begin
                            pc <= {din, tmp8};
                            ph <= P_FETCH;
                            step <= 6'd0;
                            elapsed <= 8'd0;
                        end
                    endcase
                end

                // take_interrupt (tlcs870.cpp:982). MAME charges it no cycles.
                P_INT: begin
                    step <= step + 6'd1;
                    case (step)
                        6'd0: `WR(sp, psw)
                        6'd1: `WR(sp - 16'd2, pc[7:0])
                        6'd2: begin `WR(sp - 16'd1, pc[15:8]) sp <= sp - 16'd3; end
                        6'd3: `RD(ea)
                        6'd4: `RD(ea + 16'd1)
                        6'd5: tmp8 <= din;
                        default: begin
                            pc <= {din, tmp8};
                            ph <= P_FETCH;
                            step <= 6'd0;
                            elapsed <= 8'd0;
                        end
                    endcase
                end

                P_FETCH: begin
                    step <= step + 6'd1;
                    case (step)
                        6'd0: begin
                            if (int_pending) begin
                                il_n[int_pri] = 1'b0;
                                eir_n[0] = 1'b0;
                                ea <= 16'hffe0 + {11'd0, ~int_pri, 1'b0};
                                ph <= P_INT;
                                step <= 6'd0;
                            end else begin
                                tmppc <= pc;
                                dbg_pc <= pc;
                                `RD(pc)
                                pc <= pc + 16'd1;
                            end
                        end
                        6'd1: ;
                        default: begin
                            op0 <= din;
                            imm_need <= d_imm;
                            imm_got <= 2'd0;
                            cycles <= d_cyc;
                            step <= 6'd0;
                            dbg_fetch <= 1'b1;
                            if (din >= 8'he0 && din <= 8'hf7) begin
                                ph <= P_PFX;                    // a prefix: more opcode bytes
                                `RD(pc)
                                pc <= pc + 16'd1;
                            end else begin
                                ph <= (d_imm == 2'd0) ? P_EXEC : P_IMM;
                                if (d_imm != 2'd0) begin
                                    `RD(pc)
                                    pc <= pc + 16'd1;
                                end
                            end
                        end
                    endcase
                end

                // A source or destination prefix whose mode is (x) or (HL+d) carries its
                // address immediate BEFORE the second opcode byte (tlcs870_ops_dst.cpp:38), so
                // that byte is taken first and the opcode read is issued behind it. The second
                // opcode byte therefore lands on step 1 or step 2, and decides the operands and
                // the cycle count.
                P_PFX: begin
                    step <= step + 6'd1;
                    if (pfx_lead_imm) begin
                        if (step == 6'd0) begin `RD(pc) pc <= pc + 16'd1; end
                        if (step == 6'd1) pimm <= din;
                    end
                    if (step == (pfx_lead_imm ? 6'd2 : 6'd1)) begin
                        op1 <= din;
                        imm_got <= 2'd0;
                        step <= 6'd0;
                        if (is_reg_pfx) begin
                            imm_need <= d_imm;
                            cycles <= d_cyc;
                            ph <= (d_imm == 2'd0) ? P_EXEC : P_IMM;
                            if (d_imm != 2'd0) begin
                                `RD(pc)
                                pc <= pc + 16'd1;
                            end
                        end else begin
                            imm_need <= d_imm;
                            // f1 and f5 are illegal for a destination, and MAME charges the
                            // extra cycle and then runs the opcode anyway (dst.cpp:49)
                            cycles <= d_cyc + base_cycles(ea_mode)
                                   + (((op0 == 8'hf1) || (op0 == 8'hf5)) ? 5'd1 : 5'd0);
                            // the read of any trailing immediate is issued at the END of
                            // P_EA, not here: its reply has to land in P_IMM
                            ph <= P_EA;
                        end
                    end
                end

                // The effective address a source or destination prefix names, shared by both
                // (get_addr, tlcs870_ops_helper.cpp:118). Every mode leaves through `ea_done`,
                // which is a step that makes no bus request of its own, so it can issue the read
                // of a trailing immediate for P_IMM.
                P_EA: begin
                    step <= step + 6'd1;
                    case (ea_mode)
                        3'd0: ea <= {8'd0, pimm};               // (x)
                        3'd1: case (step)                       // (PC+A)
                            6'd0: `RD(ra_a)
                            6'd1: ;
                            default: ea <= tmppc + 16'd2 + {8'd0, din};
                        endcase
                        default: case (step)                    // the register pair forms
                            6'd0: `RD(ra_ea0)
                            6'd1: `RD(ra_ea1)
                            6'd2: begin
                                if (ea_mode == 3'd5) `RD(ra_c)
                                tmp16[7:0] <= din;
                            end
                            6'd3: tmp16[15:8] <= din;
                            6'd4: begin
                                case (ea_mode)
                                    3'd4: ea <= tmp16 + {8'd0, pimm};
                                    3'd5: ea <= tmp16 + {8'd0, din};
                                    3'd6: begin ea <= tmp16; acc <= tmp16 + 16'd1; end
                                    3'd7: begin ea <= tmp16 - 16'd1; acc <= tmp16 - 16'd1; end
                                    default: ea <= tmp16;       // (DE) and (HL)
                                endcase
                                // (HL+) and (-HL) write the moved pointer back
                                if (ea_mode == 3'd6 || ea_mode == 3'd7)
                                    `WR(ra_ea0, (ea_mode == 3'd6) ? (tmp16[7:0] + 8'd1)
                                                                  : (tmp16[7:0] - 8'd1))
                            end
                            6'd5: `WR(ra_ea1, acc[15:8])
                            default: ;
                        endcase
                    endcase
                    if (step == ea_done) begin
                        if (imm_need != 2'd0) begin `RD(pc) pc <= pc + 16'd1; end
                        ph <= (imm_need == 2'd0) ? P_EXEC : P_IMM;
                        step <= 6'd0;
                    end
                end

                // the operand bytes, in the order the handlers READ8() them
                P_IMM: begin
                    step <= step + 6'd1;
                    if (step == 6'd0) begin
                        if (imm_need != 2'd1) begin `RD(pc) pc <= pc + 16'd1; end
                    end else begin
                        case (imm_got)
                            2'd0: imm0 <= din;
                            2'd1: imm1 <= din;
                            default: imm2 <= din;
                        endcase
                        if (imm_got + 2'd1 == imm_need) begin
                            ph <= P_EXEC;
                            step <= 6'd0;
                        end else begin
                            imm_got <= imm_got + 2'd1;
                            if (imm_got + 2'd2 < imm_need) begin
                                `RD(pc) pc <= pc + 16'd1;
                            end
                        end
                    end
                end

                // ---- execute: the microcode word `uw` for this step ------------------------------
                P_EXEC: begin
                    if (u_bad) begin
                        dbg_unimpl <= 1'b1;
                        `FIN
                    end else begin
                        case (u_bus)
                            B_RD:    `RD(u_addr)
                            B_RDX:   `RDX(u_addr, 1'b1)
                            B_WR:    `WR(u_addr, u_wd)
                            default: ;
                        endcase

                        case (u_ld)
                            5'd1:  tmp8 <= din;
                            5'd2:  tmp8 <= din + 8'd1;
                            5'd3:  tmp8 <= din - 8'd1;
                            5'd4:  tmp8 <= din & imm0;
                            5'd5:  tmp8 <= {5'd0, din[2:0]};
                            5'd6:  tmp16[7:0] <= din;
                            5'd7:  tmp16[15:8] <= din;
                            5'd8:  ea[7:0] <= din;
                            5'd9:  ea[15:8] <= din;
                            5'd10: begin sh_v <= din; sh_op <= u_shop; end
                            5'd11: begin alu_a <= {8'd0, din}; alu_b <= {8'd0, imm0};
                                         alu_op <= u_aluop; alu_wide <= 1'b0; end
                            5'd12: begin alu_a <= {8'd0, tmp8}; alu_b <= {8'd0, din};
                                         alu_op <= u_aluop; alu_wide <= 1'b0; end
                            5'd13: begin alu_a <= tmp16; alu_b <= ea;
                                         alu_op <= u_aluop; alu_wide <= 1'b1; end
                            5'd14: begin alu_a <= tmp16; alu_b <= {imm1, imm0};
                                         alu_op <= u_aluop; alu_wide <= 1'b1; end
                            5'd15: begin tmp16 <= {8'd0, din}; acc <= 16'd0; mcnt <= 8'd0; end
                            5'd16: tmp16 <= {din, 8'd0};
                            5'd17: begin
                                tmp16 <= tmp16 | {8'd0, tmp8};
                                ea    <= {8'd0, din};
                                acc   <= 16'd0;
                                mcnt  <= 8'd0;
                            end
                            5'd18: ea <= tmp16 + 16'd1;
                            5'd19: ea <= tmp16 - 16'd1;
                            5'd20: tmp8 <= {tmp8[3:0], din[3:0]};      // ROLD: (src)
                            5'd21: tmp8 <= {din[3:0], tmp8[7:4]};      // RORD: (src)
                            5'd22: sp[7:0] <= din;
                            5'd23: sp[15:8] <= din;
                            default: ;
                        endcase

                        case (u_flag)
                            5'd1:  f <= f | FLAG_J;
                            5'd2:  f <= (f & ~FLAG_Z) | FLAG_J | ((din == 8'd0) ? FLAG_Z : 8'd0);
                            5'd3:  f <= (f & ~FLAG_Z) | FLAG_J | ((tmp8 == 8'd0) ? FLAG_Z : 8'd0);
                            5'd4:  f <= alu_f;
                            5'd5:  f <= sh_f;
                            5'd6:  f <= set_zj(f, tmp8 == 8'd0);
                            // DEC: JF follows 0xff, ZF zero
                            5'd7:  f <= (f & ~(FLAG_Z | FLAG_J))
                                      | ((tmp8 == 8'hff) ? FLAG_J : 8'd0)
                                      | ((tmp8 == 8'd0) ? FLAG_Z : 8'd0);
                            // SET/CLR/CPL: the flags follow the bit's ORIGINAL value
                            5'd8:  f <= set_zj(f, !u_bit);
                            // LD CF: CF is the bit and JF its inverse
                            5'd9:  f <= u_bit ? ((f & ~FLAG_J) | FLAG_C) : ((f & ~FLAG_C) | FLAG_J);
                            // XOR CF: the new carry is the old one against the bit; JF follows it
                            5'd10: f <= (cf ^ u_bit) ? (f | FLAG_C | FLAG_J) : (f & ~(FLAG_C | FLAG_J));
                            5'd11: f <= (f & ~FLAG_C) | FLAG_J;
                            5'd12: f <= (f & ~FLAG_J) | FLAG_C;
                            5'd13: f <= cf ? ((f & ~FLAG_C) | FLAG_J) : ((f & ~FLAG_J) | FLAG_C);
                            5'd14: f <= (f & ~(FLAG_C | FLAG_Z | FLAG_J))
                                      | ((tmp16[15:8] != 8'd0) ? FLAG_C : 8'd0)
                                      | ((acc[7:0] == 8'd0) ? (FLAG_Z | FLAG_J) : 8'd0);
                            5'd15: f <= set_zj(f, ea == 16'd0);
                            // DEC rr: JF follows 0xffff, ZF zero
                            5'd16: f <= (f & ~(FLAG_Z | FLAG_J))
                                      | ((ea == 16'hffff) ? FLAG_J : 8'd0)
                                      | ((ea == 16'd0) ? FLAG_Z : 8'd0);
                            5'd17: f <= (f & ~(FLAG_Z | FLAG_J | FLAG_C))
                                      | ((din == tmp8) ? (FLAG_Z | FLAG_J) : 8'd0)
                                      | ((din < tmp8) ? FLAG_C : 8'd0);
                            5'd18: begin f <= {din[7:4], 4'd0}; rbs <= din[3:0]; end
                            5'd19: begin rbs <= imm0[3:0]; f <= f | FLAG_J; end
                            default: ;
                        endcase

                        case (u_sp)
                            3'd1:    sp <= sp - 16'd1;
                            3'd2:    sp <= sp - 16'd2;
                            3'd3:    sp <= sp - 16'd3;
                            3'd4:    sp <= sp + 16'd1;
                            3'd5:    sp <= sp + 16'd2;
                            3'd6:    sp <= sp + 16'd3;
                            3'd7:    sp <= {imm1, imm0};
                            default: ;
                        endcase

                        case (u_pc)
                            4'd1: pc <= tmp16;
                            4'd2: pc <= {din, tmp8};
                            4'd3: pc <= {imm1, imm0};
                            4'd4: if (cond_met(op0[2:0], f)) begin                // JR cc
                                pc <= jr_target;
                                cycles <= cycles + 5'd2;
                            end
                            4'd5: if (cond_met(op0[5] ? 3'd7 : 3'd6, f)) begin    // JRS F / JRS T
                                pc <= jrs_target;
                                cycles <= cycles + 5'd2;
                            end
                            4'd6: pc <= jr_target;
                            // MAME jumps to the vector's ADDRESS, not through it (tlcs870_ops.cpp:985)
                            4'd7: pc <= 16'hffc0 + {11'd0, op0[3:0], 1'b0};
                            4'd8: pc <= 16'hff00 + imm0_a;
                            4'd9: pc <= {din, tmp16[7:0]};
                            default: ;
                        endcase

                        case (u_misc)
                            3'd1:    eir_n[0] = 1'b1;                  // RETI: always re-enabled
                            3'd2:    il_n[1] = 1'b1;                   // SWI
                            3'd3:    dbg_unimpl <= 1'b1;
                            default: ;
                        endcase

                        case (u_seq)
                            Q_FIN: `FIN
                            // handle_mul: only the flags are observable (the registers are
                            // written back unchanged, tlcs870_ops_helper.cpp:91); shift-and-add
                            Q_MUL: if (u_muldone) begin
                                f <= set_zj(f, acc[15:8] == 8'd0);
                                `FIN
                            end else begin
                                if (tmp8[0]) acc <= acc + tmp16;
                                tmp8  <= {1'b0, tmp8[7:1]};
                                tmp16 <= {tmp16[14:0], 1'b0};
                                mcnt  <= mcnt + 8'd1;
                            end
                            // handle_div (tlcs870_ops_helper.cpp:52): restoring, 16 steps; the
                            // quotient's low byte goes to the register this step names
                            Q_DIV: if (u_div0) begin
                                f <= f | FLAG_C;                       // divide by zero
                                `FIN
                            end else if (u_divdone) begin
                                `WR(u_ra, tmp16[7:0])
                            end else begin
                                if ({acc[14:0], tmp16[15]} >= {8'd0, ea[7:0]}) begin
                                    acc   <= {acc[14:0], tmp16[15]} - {8'd0, ea[7:0]};
                                    tmp16 <= {tmp16[14:0], 1'b1};
                                end else begin
                                    acc   <= {acc[14:0], tmp16[15]};
                                    tmp16 <= {tmp16[14:0], 1'b0};
                                end
                                mcnt <= mcnt + 8'd1;
                            end
                            default: ;
                        endcase
                    end
                end

                default: begin                  // P_PACE
                    if (elapsed >= {3'd0, cycles}) begin
                        ph <= P_FETCH;
                        step <= 6'd0;
                        elapsed <= ce ? 8'd1 : 8'd0;
                    end
                end
            endcase
        end

        il  <= il_n;
        eir <= eir_n;
        a_q  <= a_d;
        rd_q <= rd_d;
        latch_q <= latch_d;
        we_q <= we_d;
        wd_q <= wd_d;
    end

`undef RD
`undef RDX
`undef WR
`undef FIN

endmodule
